/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutocompleteTag: typeof import('./src/components/AutocompleteTag.vue')['default']
    BaseNavbar: typeof import('./src/components/BaseNavbar.vue')['default']
    LazyLoadImage: typeof import('./src/components/LazyLoadImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
