/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccB: typeof import('./src/components/AccB.vue')['default']
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    AutocompleteTag: typeof import('./src/components/AutocompleteTag.vue')['default']
    AutoTag: typeof import('./src/components/AutoTag.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BaseNavbar: typeof import('./src/components/BaseNavbar.vue')['default']
    BasePagination: typeof import('./src/components/BasePagination.vue')['default']
    LazyLoadImage: typeof import('./src/components/LazyLoadImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
}
