/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    AutocompleteTag: typeof import('./src/components/AutocompleteTag.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BaseOverlay: typeof import('./src/components/BaseOverlay.vue')['default']
    BasePagination: typeof import('./src/components/BasePagination.vue')['default']
    LazyLoadImage: typeof import('./src/components/LazyLoadImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionAbout: typeof import('./src/components/main/SectionAbout.vue')['default']
    SectionFeatures: typeof import('./src/components/main/SectionFeatures.vue')['default']
    SectionHome: typeof import('./src/components/main/SectionHome.vue')['default']
    SectionInquiry: typeof import('./src/components/main/SectionInquiry.vue')['default']
    SectionInspection: typeof import('./src/components/main/SectionInspection.vue')['default']
    SectionLivery: typeof import('./src/components/main/SectionLivery.vue')['default']
    SectionSale: typeof import('./src/components/main/SectionSale.vue')['default']
  }
}
